### ISSUE TITLE
Automatická autentizace

### ISSUE THREAD

**Issue by vitkolos** [bakalari-api/bakalari-api-v3#13]
V mobilní aplikaci je tlačítko (vpravo nahoře), které uživatele odkáže na adresu **/api/3/login/TOKEN?returnUrl=dashboard**. Nepodařilo se někomu zjistit, co je to za token? Zkoušel jsem refresh, ale nefunguje.

**Comment by Lastaapps** [comment]
Vim, mám to už zdokumentovaný, jen to uploadovat. Dodělám to a za "chvíli" to tu bude

**Comment by vitkolos** [comment]
Moc děkuju, opravdu mi to hodně pomohlo.
