### ISSUE TITLE
Dá se zjistit seznam všech škol, které používají Bakaláře a jejich URL?

### ISSUE THREAD

**Issue by MaTY-MT** [bakalari-api/bakalari-api-v3#20]
API Potřebuje dávat requesty na specifickou doménu té školy, aby se přihlásil uživatel z té školy. Nejde používat třeba doména jen jedné školy, protože by nešel login ostatních userů z ostatních škol. Má otázka zní:
je někde seznam všech škol, které používají Bakaláře a jejich domény? Bylo by potom mnohem lehčí pro uživatele, aby tam měl jen dropdown a on si vybral školu svoji, než tam musel dávát dlouhou doménu té školy.

**Comment by vitkolos** [comment]
Duplicate of https://github.com/bakalari-api/bakalari-api/issues/38
