### ISSUE TITLE
Campaign, reklamy (informační kanál?)

### ISSUE THREAD

**Issue by vitkolos** [bakalari-api/bakalari-api-v3#23]
Zkoumal jsem, jaké requesty se posílají ve webové aplikaci, a vypadá to, že endpoint [campaign (https://campaign.bakalari.cz/bannerinfo/$Location/$CampaignCategoryCode)](https://github.com/bakalari-api/bakalari-api-v3/blob/master/campaign.md) slouží k získávání dat o reklamách (tedy dat ke generování/zobrazování reklamních bannerů). V dokumentaci tomu říkáme informační kanál, nejsem si jistý, jestli je to úplně vhodné označení, ale budiž. 😄 

Dost informací se dá zjistil ze skriptu **/next/js/Widgets/Commercial.js**.

Jinak z pozorování, které jsem provedl ve webové aplikaci jsem zjistil, že kromě $Location může mít kromě `mobileapp` ještě hodnoty `LargeBanner` a `SmallBannersPanel`. Druhou zajímavostí je pro mě fakt, že se $CampaignCategoryCode liší od toho mobilního – v mém případě je tam totiž zakódovaná špatná hodnota roku studia, konkrétně `"sy":12`.

Na základě zmíněného JSONu jsem zrekonstruoval pravděpodobnou strukturu dat:

```json
{
    "banners": [
        {
            "messageId": 123,
            "linkUrl": "https://www.example.com",
            "authorized": true,
            "imageUrl": "https://www.example.com/image.png",
        },
        {
            "messageId": 456,
            "linkUrl": "https://www.example.com/xyz",
            "authorized": false,
            "imageUrl": "https://www.example.com/image2.png",
        }
    ]
}
```

Zajímalo by mě, jak se chová vaše webová aplikace a jestli si myslíte, že má smysl něco takového zanést do dokumentace.

**Comment by Lastaapps** [comment]
Ahoj,
popsané divné chování webové verze mám taky (web `"sy":13`, mobil `"sy":4`). Hodnotu 13 bych asi viděl jako dobu studia včetně základní školy.
Název modulu jsem usuzoval podle mobilní sekce Infokanál, pro kterou jsem nenašel adekvátní školami hostovaný endpoint + u mě nezobrazovala žádná data, stejně jako odpověď z "bannerů" + v anglickém překladu má hlášku `"There are currently no campaigns available"`, což mi krásně ladilo s `CampaignCategoryCode` z modulu user. Ve světle nových informací ale nemám problém s přejmenováním modulu na něco výstižnějšího, případně dodání poznámky, že jde o reklamu.
Na závěr k dokumentaci, určitě bych to doplnil, nemusí se nedokumentovat pouze mobilní aplikace. Na škodu to tam nebude.

**Comment by vitkolos** [comment]
To s tou základní školou je dobrý poznatek, nějak mi to nedošlo. 😄 Přijde mi rozumné zdokumentovat to do toho souboru campaign.md – až budu mít čas, mrknu na to.

K infokanálu – možná dává smysl, že by to s tím endpointem souviselo. Ale obecně myšlenka reklam v Bakalářích mi přijde zvláštní, protože je to software, který si platí samy školy a Bakaláři tedy asi nepotřebují používat reklamy jako zdroj financí…

**Comment by vitkolos** [comment]
Dneska se mi konečně podařilo získat autentická data. 😀 
```json
{
    "banners": [
        {
            "messageId": 1049,
            "imageUrl": "https://www.bakalari.cz/images/kampane/NadaceAlbatros-TalentifyMe-Rodic-340x330.jpg",
            "linkUrl": "https://www.talentify.me/cs-cz",
            "priority": 50
        }
    ]
}
```
