### ISSUE TITLE
Způsob jak sniffovat requesty

### ISSUE THREAD

**Issue by mvolfik** [bakalari-api/bakalari-api-v3#25]
V bakalari-api/bakalari-api#51 je zmíněné že nová aplikace ignoruje systémovou proxy, tak jsem jenom chtěl zmínit šikovný způsob jak to lze (po úvodním setupu jednoduše) odposlouchávat:

1. Budete potřebovat veřejnou doménu. Můžete použít subdoménu nějaké kterou už máte, nebo si jednu sehnat zadarmo na freenom.com (.tk, .cf apod)
2. Pro danou doménu přes [Let's Encrypt certbota](https://certbot.eff.org/docs/install.html#running-with-docker) získejte ssl certifikát (aplikace nefunguje jen přes http)
3. `cat /path/to/certbot/live/vase-domena.tk/fullchain.pem /path/to/certbot/live/vase-domena.tk/privkey.pem > bundle.pem`
3. Stáhněte si [mitmproxy](https://mitmproxy.org/)
4. Změnte DNS záznam té domény na IP adresu vašeho počítače na lokální síti (10.0.0.x, 192.168.0.x apod)
5. `sudo mitmproxy --mode reverse:https://bakalari.vaseskola.cz --certs vase-domena.tk=/cesta/k/bundle.pem -p 443` (sudo je potřeba abyste mohli bindovat port 443)
6. Spusťte na stejné lokální síti aplikaci, zadejte přihlašovací údaje pro vaší školu, ale použijte tu vaši doménu, která směřuje na váš počítač.
7. ~~Profit~~ Vidíte veškerý traffic, případně můžete requesty zastavovat a upravovat request/response, viz dokumentace mitmproxy.

**Comment by Czechball** [comment]
Kromě tohohle způsobu lze ještě použít aplikaci [HttpCanary](https://play.google.com/store/apps/details?id=com.guoshi.httpcanary), která byla ale zřejmě bohužel odebrána z obchodu Google Play - pro svoji funkci vyžaduje root, ale Bakaláři v ní fungují v pořádku. Další nevýhoda je paywall pokročilých funkcí, ale pro reverse engineering Bakaláři API postačí i free verze.

![photo_2021-03-23_06-55-03](https://user-images.githubusercontent.com/13371865/112100036-c91dc180-8ba4-11eb-9b5c-0fff0235eaeb.jpg)

**Comment by PanJohnny** [comment]
A ještě můžeš použít chrome webtools. Je tam network tab, který je sniffuje.
