### ISSUE TITLE
Room a Teacher ID -> jméno

### ISSUE THREAD

**Issue by Patrik-svobodik** [bakalari-api/bakalari-api-v3#28]
Je nějaký endpoint, který by mi dokázal buďto vrátil list všech učitelů/místností nebo info o daném učiteli podle ID? Nikde v dokumentaci jsem nenašel něco, co by mi s tímto pomohlo

**Comment by mariansam** [comment]
Je ta funkcionalita v oficiální aplikaci? Já to tam nevidím, takže asi nebude ani endpoint.

**Comment by Patrik-svobodik** [comment]
Oficiální aplikace dokáže zobrazit jméno učebny a učitele v rozvrhu (API vrací pouze ID), takže někde asi něco bude, ale zatím se mi nepodařilo vypátrat jak tyto data získává

**Comment by Lastaapps** [comment]
Pokud tě zajímají data z rozvrhu, tak hledej na [konci tohohle jsonu.](https://github.com/bakalari-api/bakalari-api-v3/blob/master/moduly/rozvrh_priklady/bezny.json). Ten by měl vracet mám za to pouze učitele potřebné pro daný týden, ne všechny.

Dále se dá seznam učitelů žáka vytáhnout z [předmětů](https://github.com/bakalari-api/bakalari-api-v3/blob/master/moduly/subjects.md).

A pokud bys chtěl všechny učitele školy, tak to bohužel nevím...

**Comment by Patrik-svobodik** [comment]
Díky moc, tohle mi bohatě stačí
