### ISSUE TITLE
Jak se přihlásit

### ISSUE THREAD

**Issue by PanJohnny** [bakalari-api/bakalari-api-v3#30]
Dobrý den koukal jsem se na login. Bohužel jse mi nevede poslat post request správně a nevím jak to spravit.

Na jaké url bych měl směřovat post a jak?

Děkuji

**Comment by vitkolos** [comment]
Ahoj, tohle issue jsi zavřel – znamená to, že už se ti problém podařilo vyřešit? Pokud by sis s čímkoliv nevěděl rady, neváhej se ozvat. ✌️ (Jo a asi si můžeme tykat.)
