### ISSUE TITLE
Po jak dlouhé době mám updatovat token

### ISSUE THREAD

**Issue by PanJohnny** [bakalari-api/bakalari-api-v3#34]
používám api/login který mi řekne, že token vyprší za `3599` vůbec nechápu co se tím bakaláři snaží říct. Jaké to jsou jednotky času? Programuji teď Java wrapper pro V3 bakaláři API a chtěl bych obnovovat token automaticky.

**Comment by Lastaapps** [comment]
Mám za to, že sekundy (1h = 3600s) - 1s

**Comment by PanJohnny** [comment]
Děkuji vyzkouším a máš cool projekty.
