### ISSUE TITLE
Baka4J - Java wrapper pro bakaláři api v3

### ISSUE THREAD

**Issue by PanJohnny** [bakalari-api/bakalari-api-v3#35]
Chci jenom sdílet můj open-source projekt. Je to wrapper pro Javu. Byl bych rád kdyby mi někdo pomohl. Zatím jsem toho moc neudělal, ale pracuji na dalších endpointech. To co bakaláři vracejí je fakt strašný. Teď dělám na známkách, ale postupně chci zpracovat vše.

Děkuji a přeji hezký den.

[Baka4J tady](https://github.com/PanJohnny/Baka4J)

**Comment by PanJohnny** [comment]
Ukázka domácích úkolů:

```java
import com.panjohnny.baka4j.BakaClient;
import com.panjohnny.baka4j.elements.Homework;

public class Test {
    public static void main(String[] args) {
        BakaClient bc = new BakaClient("SCHOOL_URL", "USER_NAME", "PASSWORD");

        for (Homework h:
                bc.requestHomeworks()) {
            // checks if homework is closed, if it is it would skip it
            if(h.closed())
                continue;
            StringBuilder sb = new StringBuilder()
                    .append(h.clazz().abbrev()).append(" ")
                    .append(h.subject().abbrev()).append(": ")
                    .append(h.content())
                    .append(" -> due to: "+h.dateEnd());
            System.out.println(sb);
        }
    }
}
```

**Comment by PanJohnny** [comment]
Tento projekt jsem přepracoval. Nově používám OKHttp a requesty jsou rešené pomocí `RestAction<T>`. Tím pádem už se nezastaví hlavní thread při načítání.
Ukázka nové verze:
https://github.com/PanJohnny/Baka4J/blob/main/src/main/java/com/panjohnny/baka4j/v3/V3Client.java

**Comment by vitkolos** [comment]
Dobrá práce! Tvůj projekt jsem přidal do README mezi ostatní aplikace a nástroje založené na API v3.
