### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by maskalix** [bakalari-api/bakalari-api-v3#36]
Dobrý den,
vytvářím Discord bota pro Bakaláře (vzhledem k velké poptávce studentů) a potýkám se s jedním zásadním problémem a totiž jak uložit přístupové údaje a napadl mne jednodušší způsob pomocí tokenu, který by si jednoduše každý student nějak vygeneroval.
Je toto nějak možné či Vás napadá lepší varianta?

Předem děkuji za odpověď
Martin S.

**Comment by ondraczsk** [comment]
Tokeny si studenti generovat nemusí, když ti je bakaláři už vytvoří...
Uložit přístupové údaje můžeš v podstatě pomocí refresh tokenu, ten slouží k znovupřihlášení (a získání access tokenu).
Když jsem vytvářel svůj projekt, ukládal jsem lokálně username a refresh token.

**Comment by vitkolos** [comment]
Přesně tak, stačí uložit refresh token. Akorát je potřeba ho dobře zabezpečit, aby ho nikdo nemohl zneužít.

**Comment by maskalix** [comment]
Tomu rozumím, ale jak odchytím právě ten refresh token? Koukal jsem například na https://www.npmjs.com/package/@godlessssss/bakalari.js (potřebuji pro JavaScript) a zde požadují jako vstupní info právě údaje, které kdyby se neuložili, ale sloužili by jen k jednorázovému vygenerování tokenu, tak bych se tedy nemusel starat o jejich uložení. Jenže netuším, jak ten token v tomto případě uložit, popř. jak ho následně využít :/

nebo existuje nějaká jiná metoda u toho JSka?
(omlouvám se, v těchto vodách trochu tápu..)

**Comment by vitkolos** [comment]
Ta knihovna vypadá, že to neumožňuje, takže doporučuju, aby ses na to API napojil sám. Můžeš si půjčit [můj kód](https://github.com/gyohavl/igoh/blob/main/prumer/prumer.html), je tam zpracované základní přihlašování a získávání dat z API Bakalářů (původně to měla být kalkulačka průměru známek, ale nedodělal jsem ji). Já tam používám fetch, ale ty můžeš klidně využít axios nebo AJAX.

**Comment by maskalix** [comment]
Děkuji za pomoc :D 
Toť odemne vše
