### ISSUE TITLE
API pro volné moduly webové aplikace

### ISSUE THREAD

**Issue by Davr1** [bakalari-api/bakalari-api-v3#40]
Ahoj,
neví někdo jestli existuje api pro [volné moduly](https://napoveda.bakalari.cz/index.html?wa_param_volne.htm)? S rozvrhem na mojí škole často bývají problémy - mobilní a webová aplikace ukazuje suplování jen dva dny dopředu, stránky školy ukazují suplování až do příštího pondělí, ale `/Timetable/public` bývá nejspolehlivější s dvoutýdenním rozsahem (i když se také někdy neshoduje).
Kromě parsování html se mi nepodařilo přijít na lepší způsob jak by se odsud dalo získat data.

**Comment by vitkolos** [comment]
Ahoj, obávám se, že k volným modulům žádné API neexistuje. API Bakalářů je totiž primárně (a asi i výhradně) určeno pro mobilní aplikace, funkce, které v aplikacích chybí, tedy v API nenajdeš. A volné moduly jsou čistě webová záležitost.

Teoreticky pro tebe může být zajímavý tenhle repozitář, kde nějakým způsobem pracuji se dvěma různými volnými moduly: https://github.com/gyohavl/igoh

**Comment by Davr1** [comment]
Tvůj projekt jsem si prohlédl, ale nedaří se mi zreplikovat requesty které ten bot posílá pro získání tabulky suplování. Vypadá to že by adresa měla být ve formátu `url/next/zmeny.aspx?getParams` ale zdá se, že to ignoruje všechny parametry. Na webu bakalářů to je naopak POST request s parametry unvitř těla. Je v tom nějaký rozdíl?
A jak často je potřeba refreshovat __VIEWSTATE?

**Comment by vitkolos** [comment]
Ta adresa po složení vypadá konkrétně přibližně takto: `https://gyohavl.bakalari.cz/next/zmeny.aspx?__VIEWSTATE=1IuNGvMfVJc0ClwLMGp…` Nevím, co myslíš tím, že to ignoruje všechny parametry – pokud je ta adresa v takovém tvaru, tak by to mělo fungovat. Rozdíl v tom asi není, já jsem použil GET parametry, protože jsem tu výslednou URL tím pádem mohl otestovat přímo v prohlížeči. 😄 

Tu adresu jsem sestavoval na základě dat, která se posílají právě v těch POST requestech, v podstatě jsem sebral všechno, co se tam posílá, a postupně jsem to umazával a sledoval jsem, co to udělá. Co se týče toho __VIEWSTATE, tak jsem moc nezkoumal, jak to funguje. Musel jsem ho změnit jenom jednou, což nějak souviselo se změnou uvnitř Bakalářů (to bylo před měsícem). Od té doby je tam ten samý.

**Comment by Davr1** [comment]
Z nějakého důvodu get requesty vracejí jen dnešní změny v rozvrhu, možná problém s encodováním speciálních znaků (`"` -> `&quot;` -> `%26quot%3B` 🥴). Post requesty fungují normálně.
Zatím je to vše, issue můžeš uzavřít :+1:

**Comment by vitkolos** [comment]
Tak ještě update: Nějaké API pro volné moduly existuje. https://www.bakalari.cz/Static/konektor

**Comment by Davr1** [comment]
Hmm, to vypadá zajímavě.
Podle popisu to zní jako kdyby to bylo jenom rozšíření pro /api/v3 - dalo by se uhodnout jaké endpointy to používá (?)
Už nějakou dobu projíždím google ale asi jedinou užitečnou věc kterou jsem našel je krátký seznam škol které datový konektor mají zapnutý - https://www.inteco4u.cz/index.php?q=reference
