### ISSUE TITLE
Získání rozvrhu na další den

### ISSUE THREAD

**Issue by Tadeas-grohmi** [bakalari-api/bakalari-api-v3#41]
Nemůžu se dostat k rozvrhu na další den, request má formát: `https://bakalari.mojeskola.cz/api/3/timetable/actual?date=2022-11-15`
Dnes je 14, pokud zadám do requestu jakýkoliv den předtím tak to normálně funguje, pokud ale zadám zítřek atd, tak to stále vypisuje dnešek. 
Je to chyba u mě?

**Comment by vitkolos** [comment]
bakalari-api/bakalari-api#57
