### ISSUE TITLE
OFFTOPIC: strava.cz

### ISSUE THREAD

**Issue by PanJohnny** [bakalari-api/bakalari-api-v3#44]
Zajímalo by mě, jak je to s backendem stravy, odhaduji že používá C#, ale nebyl jsem schopný najít jakýkoliv API endpoint.

Pro vlastní účely jsem doposud scrapoval jídelníček a hodil jsem ho do svého [projektu](https://fastgymlit.vercel.app/jidelnicek).

Zajímalo by mě, jestli se dá dostat na tyto informace i bez scrapování.

Přikládám odkaz na to jak to scrapuju s JS dom: https://github.com/PanJohnny/FastGymlit/blob/master/src/pages/jidelnicek.astro

**Comment by Lastaapps** [comment]
Takže se v podstatě samozřejmě pouze pro vědecké účely ptáš, jak reverse engineerovat jejich Android API?

**Comment by vojta-dev** [comment]
Strava má API na mobily (a jejich [modernizovanou aplikaci](https://aplikace.strava.cz/)), které však potřebuje jméno a heslo na zobrazení jídelníčku (možná to nějak jde i bez credentials, ale mě se nepodařilo nic najít), takže bys musel posílat 2 requesty místo jednoho.

Nebo je tu druhá možnost, která nepotřebuje přihlášení: (nahraď 0000 svojí jídelnou)
```
curl --http0.9 "http://www.strava.cz/foxisapi/foxisapi.dll/istravne.istravne.process?xmljidelnickyA&zarizeni=0000"
```

Obě možnosti vrací XML, ale u té druhé stačí jen jeden request a je to.

**Comment by Lastaapps** [comment]
Osobně v těhle podnicích nejím a neznám je, takže tohle asi bude moje poslední zpráva k tématu.

Obecně poslat 2 requesty bych nepovažoval za zas takovou bolest (tzn. nebránil bych se tomu),
ale samozřejmě závisí na situaci a pokud ti dá vše potřebná 1 call, tak pohoda.

A k API, pokud by jsi by v Minecraftu se chtěl podívat, co volá nějaká Android aplikace (na IOS počítám nepochodíš),
tak buďto vezmeš mobil s dostatečně starou verzí Androidu (asi do 7.1, nvm přesně už), nebo musíš ohackovat emulátor v android studiu a pak se pomocí HttpCanary nebo Wiresharku podíváš na provoz.

Významně pochybuji, že bude jejich API někde veřejná či že ti ji na vyžádání (zdarma) poskytnou.

Hodně zdaru při řekněme výzkumu.

**Comment by Lastaapps** [comment]
A zase odpovídám špatné osobě 😅
Ale mazat to to už nechci.

**Comment by PanJohnny** [comment]
Vpohodě 😅. Samozřejmě pro vědecké účely, myslím že to s tím snifováním reauestů jde i přes rootování telefonu ne? Válí se mi tady jeden starej no...

**Comment by Lastaapps** [comment]
Pravda, na root jsem zapoměl, jak jsem ho tehdy neměl.

**Comment by Lastaapps** [comment]
Pravda, na root jsem zapomněl, jak jsem ho tehdy neměl.

**Comment by PanJohnny** [comment]
Jo a o nový stravě jsem nevěděl, je to třicetkrát lepší. Děkuji tady všem za odpovědi uzavírám to tu.
