### ISSUE TITLE
Podmínky pro použití API

### ISSUE THREAD

**Issue by petrvosahlocom** [bakalari-api/bakalari-api-v3#50]
Dobrý den,
rád bych se zeptal na podmínky použití API aplikace Bakaláři. Konkrétně mě zajímá:

1. Jaké jsou podmínky a požadavky pro používání API aplikace Bakaláři?
2. Je povoleno využívat API aplikace Bakaláři pro komerční účely?

Předem děkuji za odpověď.

**Comment by ondraczsk** [comment]
Ahoj,
Bakaláři API nazývají jako ✨Datový konektor✨. Zde jsou vypsány podmínky používání: https://www.bakalari.cz/Static/konektor

**Comment by vitkolos** [comment]
Ahoj @ptrvc,
jsou to dobré otázky, akorát tady na ně nedostaneš žádnou autoritativní odpověď. Tu ti můžou dát jenom zástupci firmy BAKALÁŘI software nebo tvé školy.

Tvé použití aplikace Bakaláři podléhá nějakým smluvním podmínkám, se kterými jsi jako uživatel souhlasil, takže ty jsou pro tebe závazné. Tvoje škola má s firmou Bakaláři taky nějakou smlouvu, jejíž součástí jsou podmínky použití, takže pokud bys to chtěl řešit s někým ze školy, ověř si, že ti lidi ty podmínky znají.

API, které je tady zdokumentované, používá oficiální mobilní aplikace Bakalářů. Jsem přesvědčen, že tohle API není určeno k žádnému jinému použití a že je zcela oddělené od [Datového konektoru](https://www.bakalari.cz/Static/konektor). Tohle API rozhodně nedoporučuju používat komerčně, k tomu fakt slouží pouze Datový konektor.
