### ISSUE TITLE
Problém s client_id

### ISSUE THREAD

**Issue by Patrik-svobodik** [bakalari-api/bakalari-api-v3#7]
Dobrý den, zkouším udělat aplikaci pro Bakaláře ale narazil jsem na problém. Hází mi to klasickou invalid_client chybu. Má tam být ANDR? Pokud ne, co tedy?

**Comment by Lastaapps** [comment]
Mně to funguje normálně s client_id=ANDR, tady tu mapu převádím na POST data a všechno jede ok.

``` kotlin
//POST data map
val dataMap = HashMap<String, String>()
dataMap["client_id"] = "ANDR"
dataMap["grant_type"] = "password"
dataMap["username"] = username
dataMap["password"] = password
val data = getPostDataString(dataMap)
```
dostanu data `"grant_type=password&username=USERNAME&password=HESLO&client_id=ANDR"`

**Comment by Patrik-svobodik** [comment]
Zatím to zkouším jen přes Postman a nejde mi to. Za chvíli pošlu ten endpoint kterej zkouším

**Comment by Lastaapps** [comment]
Já jsem to prvotně testoval přes curl, jede to v pohodě
`curl -i -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=password&username=USERNAME&password=PASSWORD&client_id=ANDR" -X POST https://skola.cz/api/login`

**Comment by Patrik-svobodik** [comment]
Můj endpoint přesně je:
`https://bakalari.zs-prazska-pe.cz/api/login?client_id=ANDR&grant_type=password&username=JMENO&password=HESLO`

**Comment by Lastaapps** [comment]
Schválně zkus přes příkazovou řádku to curl co jsem posílal, jestli to pujde

`curl -i -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=password&username=USERNAME&password=PASSWORD&client_id=ANDR" -X POST https://bakalari.zs-prazska-pe.cz/api/login`

Tam kam moje skromné znalosti o `GET` a `POST` metodách sahají, tak na školní server posíláš `GET` požadavek, který u login modulu nefunguje, proto to nebere data z linku a tudíž to nevidí ani `client_id` a `grant_type`.

Abys to rozchodil, musíš provést `POST` požadavek. V tom se data přenáší mimo url, v datovém toku a server je bude schopen zpracovat a odpovědět. S Postmanem jsem nedělal, nevím jak to tam nastavit, ale je to celkem častý, takže to bude celkem vidět. V Javě po navázání připojení otevřeš odchozí datový proud a tam zapíšeš `"grant_type=password&username=USERNAME&password=PASSWORD&client_id=ANDR"`

**Comment by Patrik-svobodik** [comment]
Teď mi došlo, že to posílám jako parametr a ne jako body. Už mi to jde.
Díky!

**Comment by Lastaapps** [comment]
Rádo se stalo
